spring.application.name=trytolist
server.port=8081

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysqlPW
spring.datasource.url=jdbc:mysql://localhost:3306/trytodb?useSSL=false&serverTimezone=UTC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect