spring.application.name=atv1
server.port=8081

# Nome da aplicação

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criar/atualizar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true

# ===============================
# ? H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# (Importante para evitar problemas em versões mais novas)
spring.jpa.defer-datasource-initialization=true